Merge functions set_led
bluerobotics/navigator-rs pull request #34
Opened 2023-07-10 18:15 UTC by RaulTrombin

*Needs Merge & Rebase:
- [ ] https://github.com/bluerobotics/navigator-rs/pull/33

Merge set_led methods to a single one.

Corrects the open milestone issue:
- [ ] https://github.com/bluerobotics/navigator-rs/issues/30

2023-07-11 01:13 UTC, joaoantoniocardoso reviewed
Seems okay, just minor observations.

2023-07-11 01:13 UTC, joaoantoniocardoso commented on src/lib.rs
> +                .unwrap_or_else(|_| panic!("Error: Set LED value to {}", state));
```Rust
panic!("Error: Set LED value to {state}");
```

2023-07-11 01:13 UTC, joaoantoniocardoso commented on src/lib.rs
>      /// loop {
isn't there a 'no_run' statement missing here?

2023-07-12 13:37 UTC, patrickelectric commented
@RaulTrombin please rebase.

2023-07-12 13:37 UTC, patrickelectric requested changes
needs rebase

2023-07-13 08:25 UTC, patrickelectric approved these changes

2023-07-13 08:25 UTC, merged