Add: Add pwm_duty_cycle multichannel
bluerobotics/navigator-rs pull request #69
Opened 2024-02-27 19:23 UTC by RaulTrombin

2024-02-28 20:19 UTC, joaoantoniocardoso approved these changes

2024-02-29 18:47 UTC, patrickelectric requested changes

2024-02-29 18:47 UTC, patrickelectric commented on src/lib.rs
> +        }
```rs
        for channel in channels {
            self.set_pwm_channel_duty_cycle(channel, duty_cycle)
        }
```

2024-02-29 18:50 UTC, patrickelectric approved these changes

2024-02-29 18:50 UTC, merged